url: "https://ahmed-fouad-lagha.github.io"
baseurl: ""

plugins:
    - jekyll-sitemap

# variables
name: Ahmed Fouad Lagha's homepage
description: Ahmed Fouad Lagha's homepage
# File management
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock"]

# Sass
sass:
    style: :compressed
    sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:

# Collections
collections:
    cv:
        output: true
        name: CV
        pos: 4
    blogs:
        output: true
        name: Blogs
        pos: 5
    games:
        output: true
        name: Games
        pos: 6
    
defaults:
    -
        scope:
            path: ""
        values:
            icon: "/assets/img/file.ico"
